[{"code":"10001","description":"Internal ErrorTransaction failed due to internal error."},
{"code":"10001","description":"Internal ErrorWarning an internal error has occurred. The transaction id may not be correct"},
{"code":"10001","description":"ButtonSource value truncated.The transaction could not be loaded"},
{"code":"10001","description":"Internal ErrorInternal Error"},
{"code":"10002","description":"Receiving Limit exceededYou've exceeded the receiving limit. This transaction can't be completed."},
{"code":"10003","description":"Missing argumentInvoice ID is required"},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Transaction refused because of an invalid argument. See additional error messages for details."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.The transaction id is not valid"},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid item URL."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.SellerRegistrationDate is invalid."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay seller feedback overall positive count."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay seller feedback overall negative count."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay seller feedback total positive count."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay seller feedback total negative count."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay seller feedback recent positive count."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay seller feedback recent negative count."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay item transaction date."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay item buyer protection type."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invalid eBay item payment hold risk."},
{"code":"10004","description":"Transaction refused because of an invalid argument. See additional error messages for details.Multiple eBay order IDs not allowed."},
{"code":"10007","description":"Permission deniedYou do not have permissions to make this API call"},
{"code":"10014","description":"API call was rate limited.The API call has been denied as it has exceeded the permissible call rate limit."},
{"code":"10215","description":"Soft Descriptor truncatedThe soft descriptor passed in was truncated"},
{"code":"10406","description":"Transaction refused because of an invalid argument. See additional error messages for details.The PayerID value is invalid."},
{"code":"10408","description":"Express Checkout token is missing.Express Checkout token is missing."},
{"code":"10409","description":"You're not authorized to access this info.Express Checkout token was issued for a merchant account other than yours."},
{"code":"10410","description":"Invalid tokenInvalid token."},
{"code":"10411","description":"This Express Checkout session has expired.This Express Checkout session has expired. Token value is no longer valid."},
{"code":"10412","description":"Duplicate invoicePayment has already been made for this InvoiceID."},
{"code":"10413","description":"Transaction refused because of an invalid argument. See additional error messages for detailsThe totals of the cart item amounts do not match order amounts."},
{"code":"10414","description":"Transaction refused because of an invalid argument. See additional error messages for details.The amount exceeds the maximum amount for a single transaction."},
{"code":"10415","description":"Transaction refused because of an invalid argument. See additional error messages for details.A successful transaction has already been completed for this token."},
{"code":"10416","description":"Transaction refused because of an invalid argument. See additional error messages for details.You have exceeded the maximum number of payment attempts for this token."},
{"code":"10417","description":"Transaction cannot complete.Instruct the customer to retry the transaction using an alternative payment method from the customer's PayPal wallet. The transaction did not complete with the customer's selected payment method."},
{"code":"10418","description":"Transaction refused because of an invalid argument. See additional error messages for details.The currencies of the shopping cart amounts must be the same."},
{"code":"10419","description":"Express Checkout PayerID is missing.Express Checkout PayerID is missing."},
{"code":"10420","description":"Transaction refused because of an invalid argument. See additional error messages for details.Express Checkout PaymentAction is missing."},
{"code":"10421","description":"This Express Checkout session belongs to a different customer.This Express Checkout session belongs to a different customer. Token value mismatch."},
{"code":"10422","description":"Customer must choose new funding sources.The customer must return to PayPal to select new funding sources."},
{"code":"10424","description":"Transaction refused because of an invalid argument. See additional error messages for details.Shipping address is invalid."},
{"code":"10426","description":"Transaction refused because of an invalid argument. See additional error messages for details.Item total is invalid."},
{"code":"10427","description":"Transaction refused because of an invalid argument. See additional error messages for details.Shipping total is invalid."},
{"code":"10428","description":"Transaction refused because of an invalid argument. See additional error messages for details.Handling total is invalid."},
{"code":"10429","description":"Transaction refused because of an invalid argument. See additional error messages for details.Tax total is invalid."},
{"code":"10431","description":"Item amount is invalid.Item amount is invalid."},
{"code":"10432","description":"Transaction refused because of an invalid argument. See additional error messages for details.Invoice ID value exceeds maximum allowable length."},
{"code":"10433","description":"Transaction refused because of an invalid argument. See additional error messages for details.Value of OrderDescription element has been truncated."},
{"code":"10434","description":"Transaction refused because of an invalid argument. See additional error messages for details.Value of Custom element has been truncated."},
{"code":"10435","description":"Transaction refused because of an invalid argument. See additional error messages for details.The customer has not yet confirmed payment for this Express Checkout session."},
{"code":"10441","description":"Transaction refused because of an invalid argument. See additional error messages for details.The NotifyURL element value exceeds maximum allowable length."},
{"code":"10442","description":"ButtonSource value truncated.The ButtonSource element value exceeds maximum allowable length."},
{"code":"10443","description":"Transaction refused because of an invalid argument. See additional error messages for details.This transaction cannot be completed with PaymentAction of Order."},
{"code":"10444","description":"Transaction refused because of an invalid argument. See additional error messages for details.The transaction currency specified must be the same as previously specified."},
{"code":"10445","description":"This transaction cannot be processed at this time. Please try again later.This transaction cannot be processed at this time. Please try again later."},
{"code":"10448","description":"Unconfirmed emailA confirmed email is required to make this API call."},
{"code":"10474","description":"Invalid DataThis transaction cannot be processed. The country code in the shipping address must match the buyer's country of residence."},
{"code":"10475","description":"Transaction refused because of an invalid argument. See additional error messages for details."},
{"code":"10481","description":"Transaction refused because of an invalid argument. See additional error messages for details.PaymentAction of Authorization is not allowed with Unilateral and Non-Credentialed authentication."},
{"code":"10482","description":"Transaction refused because of an invalid argument. See additional error messages for details.PaymentAction of Order is not allowed with Unilateral and Non-Credentialed authentication."},
{"code":"10485","description":"Payment not authorizedPayment has not been authorized by the user."},
{"code":"10486","description":"This transaction couldn't be completed.This transaction couldn't be completed. Please redirect your customer to PayPal."},
{"code":"10537","description":"Risk Control Country Filter FailureThe transaction was refused because the country was prohibited as a result of your Country Monitor Risk Control Settings."},
{"code":"10538","description":"Risk Control Max Amount FailureThe transaction was refused because the maximum amount was exceeded as a result of your Maximum Amount Risk Control Settings."},
{"code":"10539","description":"Payment declined by your Risk Controls settings: PayPal Risk Model.Payment declined by your Risk Controls settings: PayPal Risk Model."},
{"code":"10631","description":"Processor WarningThe authorization is being processed."},
{"code":"10725","description":"Shipping Address Country ErrorThere was an error in the Shipping Address Country field"},
{"code":"10727","description":"Shipping Address1 EmptyThe field Shipping Address1 is required"},
{"code":"10728","description":"Shipping Address City EmptyThe field Shipping Address City is required"},
{"code":"10729","description":"Shipping Address State EmptyThe field Shipping Address State is required"},
{"code":"10730","description":"Shipping Address Postal Code EmptyThe field Shipping Address Postal Code is required"},
{"code":"10731","description":"Shipping Address Country EmptyThe field Shipping Address Country is required"},
{"code":"10736","description":"Shipping Address Invalid City State Postal CodeA match of the Shipping Address City, State, and Postal Code failed."},
{"code":"11001","description":"Exceeds maximum length.Value of NoteText element is truncated."},
{"code":"11084","description":"User does not have a good funding source with which to pay.User does not have a good funding source with which to pay."},
{"code":"11302","description":"Cannot pay selfThe transaction was refused because you cannot send money to yourself."},
{"code":"11450","description":"Billing Agreement creation failedFailed to create Billing Agreement; reference transaction feature may be unavailable or not enabled for the merchant, or a system error may have occurred."},
{"code":"11607","description":"Duplicate request for specified Message Submission ID.The specified Message Submission ID (specified in MSGSUBID parameter) is a duplicate; result parameters of the original request are attached."},
{"code":"11607","description":"Duplicate RequestA successful transaction has already been completed for this token."},
{"code":"11610","description":"Payment Pending your review in Fraud Management FiltersPayment Pending your review in Fraud Management Filters"},
{"code":"11611","description":"Transaction blocked by your settings in FMFTransaction blocked by your settings in FMF"},
{"code":"11612","description":"Could not process your request to accept/deny the transactionCould not process your request to accept/deny the transaction"},
{"code":"11820","description":"Transaction refused because of an invalid argument. See additional error messages for detailsInvalid Order URL."},
{"code":"11821","description":"Invalid shipping optionsInvalid shipping options; you must specify a name and amount for each shipping option type"},
{"code":"11826","description":"Invalid shipping totalInvalid shipping total; it should equal the shipping amount of the selected shipping option"},
{"code":"12125","description":"PP incentive no longer available.There's a problem with the redemption code(s) you entered and can't be used at this time. Your payment has not been processed. Please go back to PayPal so that the code(s) can be removed, your order total can be updated and then you'll be able to complete checkout."},
{"code":"12126","description":"Payment could not be processed at this time. Incentive temporarily unavailable.We're having problems processing redemption codes at this time. Your payment has not been processed. You can try to check out again at a later time or complete your payment without the discount applied."},
{"code":"12201","description":"Immediate Payment item was not found.The item specified is either not valid or is not currently available for purchase as an Immediate Payment item."},
{"code":"12203","description":"Instant payment required for 3PXO.Instant Payment in 3PXO cannot be pending. The transaction has been rolled back."},
{"code":"12204","description":"Transaction reversed.Error occurred causing transaction reversal."},
{"code":"12206","description":"The value of PaymentAction must be Sale for Immediate Payment item.Order and Authorization are not acceptable values for PaymentAction when the item is an Immediate Payment"},
{"code":"12207","description":"Cart ID is required for Immediate Payment item.Cart ID is required for Immediate Payment item."},
{"code":"12208","description":"eBay item amount does not match Express Checkout API item amount.eBay item amount does not match Express Checkout API item amount."},
{"code":"13100","description":"Parallel payments functionality is not availableParallel payments functionality is not available"},
{"code":"13101","description":"Invalid DataPayment action of Order is only supported for parallel payments"},
{"code":"13102","description":"Payment Request ID is missingPayment Request ID is mandatory for parallel payments"},
{"code":"13103","description":"Duplicate Payment Request ID passedPayment Request ID must be unique for parallel payments"},
{"code":"13104","description":"Transaction refused because of an invalid argument. See Additional error messages for details.Number of payment requests exceeds maximum number of supported requests."},
{"code":"13106","description":"Invalid DataYou cannot pass both the new and deprecated PaymentAction parameter."},
{"code":"13107","description":"Parallel payments partially successful.One or more payment requests failed. Check individual payment responses for more information."},
{"code":"13110","description":"Multi Payments Sale is Not allowedDue to some technical difficulties the Multi Payments for Sale is not available now please try again later."},
{"code":"13111","description":"Mixed Payment action not supportedThe Payment Action passed should be unique, mixed Payment Action not supported"},
{"code":"13113","description":"Buyer Cannot Pay.The Buyer cannot pay with PayPal for this transaction."},
{"code":"13115","description":"Seller ID MissingSeller ID is mandatory for parallel payments"},
{"code":"13116","description":"Transaction refused because of an invalid argument. See additional error messages for details.The transaction is in progress for this token."},
{"code":"13122","description":"Transaction refusedThis transaction cannot be completed because it violates the PayPal User Agreement."},
{"code":"13751","description":"Could not provide identical response to original transaction.Original transaction completed successfully; however, this response differs from the original response."},
{"code":"17200","description":"Insufficient funds.Funding Instrument is invalid."},
{"code":"17203","description":"Invalid funding instrument.Funding Instrument is invalid."},
{"code":"17204","description":"Funding instrument expired."}
]