[{"code":"101", "description":"Tarjeta Caducada"},
{"code":"102", "description":"Tarjeta en excepción transitoria o bajo sospecha de fraude"},
{"code":"104", "description":"Operación no permitida para esa tarjeta o terminal."},
{"code":"106", "description":"Intentos de PIN excedidos."},
{"code":"116", "description":"Disponible Insuficiente"},
{"code":"118", "description":"Tarjeta no Registrada"},
{"code":"125", "description":"Tarjeta no efectiva."},
{"code":"129", "description":"Código de seguridad (CVV2/CVC2) incorrecto."},
{"code":"180", "description":"Tarjeta ajena al servicio."},
{"code":"184", "description":"Error en la autenticación del titular."},
{"code":"190", "description":"Denegación sin especificar motivo."},
{"code":"191", "description":"Fecha de caducidad errónea."},
{"code":"202", "description":"Tarjeta en excepción transitoria o bajo sospecha de fraude con retirada de tarjeta."},
{"code":"904", "description":"Comercio no registrado en FUC."},
{"code":"909", "description":"Error de sistema."},
{"code":"912", "description":"Emisor no Disponible."},
{"code":"9912", "description":"Emisor no Disponible."},
{"code":"913", "description":"Pedido repetido."},
{"code":"944", "description":"Sesión Incorrecta."},
{"code":"950", "description":"Operación de devolución no permitida."},
{"code":"9064", "description":"Número de posiciones de la tarjeta incorrecto."},
{"code":"9078", "description":"No existe método de pago váido para esa tarjeta."},
{"code":"9093", "description":"Tarjeta no existente."},
{"code":"9094", "description":"Rechazo servidores internacionales."},
{"code":"9104", "description":"Comercio con “titular seguro” y titular sin clave de compra segura."},
{"code":"9218", "description":"El comercio no permite op. seguras por entrada /operaciones."},
{"code":"9253", "description":"Tarjeta no cumple el check-digit."},
{"code":"9256", "description":"El comercio no puede realizar preautorizaciones"},
{"code":"9257", "description":"Esta tarjeta no permite operativa de preautorizaciones"},
{"code":"9261", "description":"Operación detenida por superar el control de restricciones en la entrada al SIS"},
{"code":"9912", "description":"Emisor no disponible."},
{"code":"9913", "description":"Error en la confirmación que el comercio envía al TPV Virtual (solo aplicable en la opción de sincronización SOAP)"},
{"code":"9914", "description":"Confirmación “KO” del comercio (solo aplicable en la opción de sincronización SOAP)"},
{"code":"9915", "description":"A petición del usuario se ha cancelado el pago."},
{"code":"9928", "description":"Anulación de autorización en diferido realizada por el SIS (proceso batch)"},
{"code":"9929", "description":"Anulación de autorización en diferido realizada por el comercio"},
{"code":"9997", "description":"Se está procesando otra transacción en SIS con la misma tarjeta."},
{"code":"9998", "description":"Operación en proceso de solicitud de datos de tarjeta."},
{"code":"9999", "description":"Operación que ha sido redirigida al emisor a autenticar."}]